### ISSUE TITLE
Proglem while ng build

### ISSUE THREAD

**Issue by MarekKu** [tonto7973/jasmine-test-cases#1]
Hello,
I have just tried your great piece of work and I was amazed how clean my test can be now. Unfortunately it has one flaw.  I installed and configured jasmine-test-cases. It works correctly while running `ng test`, but while `ng build` I got **ERROR in No NgModule metadata found for 'AppModule'**.  When commenting out 
```
"files": [
      "node_modules/jasmine-test-cases/register.d.ts"
    ]
```
in tsconfig.json `ng build` works correctly but, `ng test`doesn't.
Could you please update readme if I miss some step or fix this problem.
Below you can find my package.json

```
"devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "^6.1.0",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.11",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "4.14.139",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine": "^3.5.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jasmine-test-cases": "^1.0.1",
```

**Comment by tonto7973** [comment]
Hi MarekKu,

With AngularCLI, the file that should get updated is actually `tsconfig.spec.json` so that the typings apply to spec files only.

I'll update the readme to reflect this, thanks for pointing this out.
